### ISSUE TITLE
require packages not supported?

### ISSUE THREAD

**Issue by agalazis** [assetgraph/assetgraph-builder#329] opened 2016-03-11 19:20 UTC
I have a package in my require config  in this manner:
```
 packages: [
        {
            name: 'CryptoJS',
            location: 'path-to/bower_components/crypto-js',
            main: 'index'
        }
    ]
```
but asset graph builder still tries to load CryptoJS from basepath and shows warnings
 am sure this is a valid configuration since the unbuilt version gets configured correctly .
Paths work correctly if not defined in an array an I am not having any issue with them

**Comment by papandreou** [comment] 2016-03-11 20:28
Which script loader are you using?

**Comment by agalazis** [comment] 2016-03-11 20:47
I am using requrejs  and I specify CryptoJS in my define function when not built everything loads correctly from my bower components directory(as configured) instead of my base path when I try to built asset graph builder complains that the file was not found in a path relative to basepath instead of the location configured for the package.The above is part of the object passed to  require.config

**Comment by papandreou** [comment] 2016-05-01 22:04
Correct, this construct is not supported :/. Sorry for the delay in getting back to you.

I'm planning on changing the way require.js is supported so that we just "shell out" to `r.js` instead of attempting to reimplment it, sort of how the `bundleSystemJs` transform was implemented. That means we'll support features like these, including all require.js plugins.

**Comment by agalazis** [comment] 2016-05-02 20:27
Plus one for this idea I have also digged in to the code but then I realised that r.js wasn't used internally , and as a result any patch could end up incorrect and maybe in the future useless. I do believe that r.js should be used internally since it will be easier to maintain requirejs functionality and make sure that we end-up with the same exact behaviour

**Comment by papandreou** [comment] 2016-07-27 05:56
Fixed on master for v5.

**Closed by papandreou** 2016-07-27 05:56 UTC

**Comment by agalazis** [comment] 2016-09-24 15:46
do you know when it will be released on npm going to check it form the github version for now(I hope it's stable enough to do a build xD)

**Comment by agalazis** [comment] 2016-09-24 16:03
Now it does respect paths configuration xD any ideas? maybe it doesn't respect the whole configuration file? should it have a specific file name  or be provided in the cli parameters

**Comment by Munter** [comment] 2016-09-24 17:07
v5 of the builder calls out to requirejs itself to resolve the config. So if something doesn't work it's nost likely that we didn't correctly pick up the requirejs configuration at all. Do you have a setup we can use to replicate this?

**Comment by agalazis** [comment] 2016-09-24 19:56
I tried to build an old project but I 'll try to create something simple so that we can see what's happening

**Comment by papandreou** [comment] 2016-09-24 20:20
@agalazis You need to explicitly install one of the 5.0.0 prereleases because they don't carry the `latest` tag. For example: `npm install assetgraph-builder@5.0.0-12`

**Comment by agalazis** [comment] 2016-09-24 21:28
I did npm install -g git+https://..

**Comment by agalazis** [comment] 2016-09-25 03:40
@Munter  @papandreou  here is a complete scenario:
https://github.com/agalazis/sample-requirejs-asset-graph-build

**Comment by papandreou** [comment] 2016-09-25 06:45
Could you remove the `requirejs.config` call from `src/app/js/app.js` and instead create an inline script right before `<script data-main="app/js/app" src="bower_components/requirejs/require.js" type="text/javascript"></script>` with this content:

```html
<script>
var require = {
	appDir: ".",
	baseUrl: "app/js",
	paths: {
		'jquery'	: '../../bower_components/jquery/dist/jquery.min',
		'bootstrap'	: '../../bower_components/bootstrap/dist/js/bootstrap.min',
		'jsrasign'	: '../../bower_components/kjur-jsrsasign/jsrsasign-latest-all-min'
	},
	packages: [
		{
			name: 'CryptoJS',
			location: '../../bower_components/crypto-js',
			main: 'index'
		}
	],
	shim: {
		bootstrap:{
			"deps": [ "jquery" ]
		},
		jsrasign: {
			'exports': "jsrasign",
			init: function() {
				return {
					KJUR: KJUR
				};
			}
		},
		
	}
};
</script>
<script data-main="app/js/app" src="bower_components/requirejs/require.js" type="text/javascript"></script>
```

**Comment by papandreou** [comment] 2016-09-25 06:48
Ah, and then you should probably change `data-main="app/js/app"` to `data-main="app"` because the `baseUrl` is in effect when the main module is loaded.

**Comment by agalazis** [comment] 2016-09-25 08:27
Thanks a ton I 'll do

**Comment by agalazis** [comment] 2016-09-25 11:31
Thank you, your tool rocks! here is the result:
https://github.com/agalazis/sample-requirejs-asset-graph-build/blob/master/build/index.html
Any idea on how to compress css? I thought there is only a nocompress flag (used when I don't want compression) xD

**Comment by Munter** [comment] 2016-09-25 12:20
So did the original code actually hit a situation we should have support for?

**Comment by agalazis** [comment] 2016-09-25 12:49
Yes with the changes that @pandreou proposed (changes are not entirely visible to git since I created a new project and pushed that) xD . The issue was that I don't have inline configuration in the html file, it was in an external file set as the main of require. The inline one works.

**Comment by papandreou** [comment] 2016-09-25 22:46
> So did the original code actually hit a situation we should have support for?

Could be worth exploring. I'm not sure r.js supports the `data-main` script reconfiguring require.js, though.

**Comment by papandreou** [comment] 2016-09-25 22:59
> Any idea on how to compress css?

That should happen automatically -- from a quick glance I can't tell why it doesn't in this case. Will have to take a closer look.

**Comment by papandreou** [comment] 2016-09-25 23:06
Actually I can tell why it doesn't happen. It's a very recently introduced regression. Fixed in https://github.com/assetgraph/assetgraph-builder/commit/62fda2c0af766906e6892f090248a07d1e5b0312

**Comment by papandreou** [comment] 2016-09-25 23:06
(I promise that things will stabilize once we have a non-prerelease out :)

**Comment by agalazis** [comment] 2016-09-25 23:09
In the past when I used r.js I was creating an external build script so i don't think that my include wouldn't make any sense in the build version anw. I was just not thinking about building when I followed that approach, but still worth mentioning in the readme. If you go down the rjs path you might allow people to specify rjs configuration file but still the point of asset graph builder is to take something that works and build it based on its existing source , as a result current behaviour makes much more sense and external build specification files are unneeded.

Thanks :)

**Comment by papandreou** [comment] 2016-09-26 06:41
@agalazis If you'd like to load some of your CSS with require.js itself, there's also support for picking up the output of the [require-css plugin](https://github.com/guybedford/require-css). Here's an example setup from the test suite: https://github.com/assetgraph/assetgraph/tree/master/testdata/transforms/bundleRequireJs/cssRequire

Here's an example of using [require-less](https://github.com/guybedford/require-less) if you prefer that: https://github.com/msiebuhr/charcod.es/blob/master/http-pub/index.html#L107-L116
